//Q. Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//   By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
// Date: Mar 8,2013
// Author: Shantanu Sarkar
#include<stdio.h>
int main()
{
	int i=1,j=0,evsum=0,ser=1;
	while(ser<4000000)
	{
		ser=j+i;
		j=i;
		i=ser;
		if(ser%2==0)
			evsum=evsum+ser;
	}
	printf("%d",evsum);
}







